Rails.application.routes.draw do
  resources :static_pages
  resources :members
  root 'static_pages#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'service_describe_path', to: 'describes#service'
  get 'service_beginner_path', to: 'describes#beginner'

  get 'new_similar_member', to: 'similar_members#new'
  get 'new2_similar_member_path', to: 'similar_members#new2'

  get 'akimoto_member', to: 'members#akimoto'
  get 'endo_member', to: 'members#endo'
  get 'hayakawa_member', to: 'members#hayakawa'
  get 'hayashi_member', to: 'members#hayashi'
  get 'higuchi_member', to: 'members#higuchi'
  get 'hoshino_member', to: 'members#hoshino'
  get 'ikuta_member', to: 'members#ikuta'
  get 'ito_member', to: 'members#ito'
  get 'iwamoto_member', to: 'members#iwamoto'
  get 'kakehashi_member', to: 'members#kakehashi'
  get 'kaki_member', to: 'members#kaki'
  get 'kanagawa_member', to: 'members#kanagawa'
  get 'kitagawa_member', to: 'members#kitagawa'
  get 'kitano_member', to: 'members#kitano'
  get 'kubo_member', to: 'members#kubo'
  get 'kuromi_member', to: 'members#kuromi'
  get 'matsuo_member', to: 'members#matsuo'
  get 'mukai_member', to: 'members#mukai'
  get 'nakamura_member', to: 'members#nakamura'
  get 'saito_member', to: 'members#saito'
  get 'sakaguchi_member', to: 'members#sakaguchi'
  get 'satoka_member', to: 'members#satoka'
  get 'satori_member', to: 'members#satori'
  get 'seimiya_member', to: 'members#seimiya'
  get 'sibata_member', to: 'members#sibata'
  get 'sinuchi_member', to: 'members#sinuchi'
  get 'suzuki_member', to: 'members#suzuki'
  get 'takayama_member', to: 'members#takayama'
  get 'tamura_member', to: 'members#tamura'
  get 'terada_member', to: 'members#terada'
  get 'tsutsui_member', to: 'members#tsutsui'
  get 'umezawa_member', to: 'members#umezawa'
  get 'wada_member', to: 'members#wada'
  get 'yakubo_member', to: 'members#yakubo'
  get 'yamashita_member', to: 'members#yamashita'
  get 'yamazaki_member', to: 'members#yamazaki'
  get 'yoda_member', to: 'members#yoda'
  get 'yoshida_member', to: 'members#yoshida'
  get 'yumiki_member', to: 'members#yumiki'

  get 'akimoto_detail_member', to: 'detail_members#akimoto'
  get 'endo_detail_member', to: 'detail_members#endo'
  get 'hayakawa_detail_member', to: 'detail_members#hayakawa'
  get 'hayashi_detail_member', to: 'detail_members#hayashi'
  get 'higuchi_detail_member', to: 'detail_members#higuchi'
  get 'hoshino_detail_member', to: 'detail_members#hoshino'
  get 'ikuta_detail_member', to: 'detail_members#ikuta'
  get 'ito_detail_member', to: 'detail_members#ito'
  get 'iwamoto_detail_member', to: 'detail_members#iwamoto'
  get 'kakehashi_detail_member', to: 'detail_members#kakehashi'
  get 'kaki_detail_member', to: 'detail_members#kaki'
  get 'kanagawa_detail_member', to: 'detail_members#kanagawa'
  get 'kitagawa_detail_member', to: 'detail_members#kitagawa'
  get 'kitano_detail_member', to: 'detail_members#kitano'
  get 'kubo_detail_member', to: 'detail_members#kubo'
  get 'kuromi_detail_member', to: 'detail_members#kuromi'
  get 'matsuo_detail_member', to: 'detail_members#matsuo'
  get 'mukai_detail_member', to: 'detail_members#mukai'
  get 'nakamura_detail_member', to: 'detail_members#nakamura'
  get 'saito_detail_member', to: 'detail_members#saito'
  get 'sakaguchi_detail_member', to: 'detail_members#sakaguchi'
  get 'satoka_detail_member', to: 'detail_members#satoka'
  get 'satori_detail_member', to: 'detail_members#satori'
  get 'seimiya_detail_member', to: 'detail_members#seimiya'
  get 'sibata_detail_member', to: 'detail_members#sibata'
  get 'sinuchi_detail_member', to: 'detail_members#sinuchi'
  get 'suzuki_detail_member', to: 'detail_members#suzuki'
  get 'takayama_detail_member', to: 'detail_members#takayama'
  get 'tamura_detail_member', to: 'detail_members#tamura'
  get 'terada_detail_member', to: 'detail_members#terada'
  get 'tsutsui_detail_member', to: 'detail_members#tsutsui'
  get 'umezawa_detail_member', to: 'detail_members#umezawa'
  get 'wada_detail_member', to: 'detail_members#wada'
  get 'yakubo_detail_member', to: 'detail_members#yakubo'
  get 'yamashita_detail_member', to: 'detail_members#yamashita'
  get 'yamazaki_detail_member', to: 'detail_members#yamazaki'
  get 'yoda_detail_member', to: 'detail_members#yoda'
  get 'yoshida_detail_member', to: 'detail_members#yoshida'
  get 'yumiki_detail_member', to: 'detail_members#yumiki'

end
